name: Android CI
on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch: ["arm64"]
      fail-fast: false

    env:
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
      VERA_KEYSTORE_PASSWORD: ${{ secrets.VERA_KEYSTORE_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Get LWJGL3
        uses: dawidd6/action-download-artifact@master
        with:
          workflow: main.yml
          path: app_pojavlauncher/src/main/assets/components/lwjgl3
          workflow_conclusion: success
          repo: Vera-Firefly/lwjgl3-build
          branch: main
          name: lwjgl

      - name: Set up JDK 21
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@main
        with:
           allow-snapshot-wrappers: true
    
      - name: Build Debug ${{matrix.arch}} .apk
        run: |
          chmod +x gradlew
          ./gradlew app_pojavlauncher:assembleDebug -Darch=${{matrix.arch}}

      - name: Upload Debug
        uses: actions/upload-artifact@main
        with:
          name: PGW-debug-${{matrix.arch}}
          path: app_pojavlauncher/build/outputs/apk/debug/*
