name: Android CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch: [ "arm64" ]
      fail-fast: false

    env:
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
      VERA_KEYSTORE_PASSWORD: ${{ secrets.VERA_KEYSTORE_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get LWJGL3
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: main.yml
          path: app_pojavlauncher/src/main/assets/components/lwjgl3
          workflow_conclusion: success
          repo: Vera-Firefly/lwjgl3-build
          branch: main
          name: lwjgl

      - uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 7.6.1

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'dragonwell'
          java-version: '17'

      - name: Build Debug ${{matrix.arch}} .apk
        run: |
          gradle :app_pojavlauncher:assembleDebug -Darch=${{matrix.arch}}

      - name: Upload Debug
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-${{matrix.arch}}
          path: app_pojavlauncher/build/outputs/apk/debug/*
