name: Android CI
on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch: [ "arm64" ]
      fail-fast: false

    env:
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
      VERA_KEYSTORE_PASSWORD: ${{ secrets.VERA_KEYSTORE_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get LWJGL3
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: main.yml
          path: app_pojavlauncher/src/main/assets/components/lwjgl3
          workflow_conclusion: success
          repo: aaaapai/lwjgl3-build
          branch: main
          name: lwjgl

      - name: chmod gradlew
        run: chmod +x gradlew
        
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build Release ${{matrix.arch}} .apk
        run: |
          ./gradlew app_pojavlauncher:assembledebug -Darch=${{matrix.arch}}

      - name: Upload Debug
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-${{matrix.arch}}
          path: app_pojavlauncher/build/outputs/apk/debug/*
