name: Android CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["arm64"]
      fail-fast: false

    env:
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
      VERA_KEYSTORE_PASSWORD: ${{ secrets.VERA_KEYSTORE_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Build Debug ${{matrix.arch}} .apk
        run: |
          chmod +x gradlew
          ./gradlew app_pojavlauncher:assembleDebug -Darch=${{matrix.arch}}

      - name: Upload Debug
        uses: actions/upload-artifact@main
        with:
          name: PGW-debug-${{matrix.arch}}
          path: app_pojavlauncher/build/outputs/apk/debug/*
