name: Android CI
on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        arch: [ "arm64" ]
      fail-fast: false

    env:
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
      VERA_KEYSTORE_PASSWORD: ${{ secrets.VERA_KEYSTORE_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get LWJGL3
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: main.yml
          path: app_pojavlauncher/src/main/assets/components/lwjgl3
          workflow_conclusion: success
          repo: aaaapai/lwjgl3-build
          branch: main
          name: lwjgl

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Release ${{matrix.arch}} .apk
        if: github.repository_owner == 'Vera-Firefly' && github.ref_name == 'main_v3'
        run: |
          chmod +x gradlew
          ./gradlew app_pojavlauncher:assemblerelease -Darch=${{matrix.arch}}

      - name: Build Debug ${{matrix.arch}} .apk
        run: |
          chmod +x gradlew
          ./gradlew app_pojavlauncher:assembleDebug -Darch=${{matrix.arch}}

      - name: Upload Release
        if: github.repository_owner == 'Vera-Firefly' && github.ref_name == 'main_v3'
        uses: actions/upload-artifact@v4
        with:
          name: app-release-${{matrix.arch}}
          path: app_pojavlauncher/build/outputs/apk/release/*

      - name: Upload Debug
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-${{matrix.arch}}
          path: app_pojavlauncher/build/outputs/apk/debug/*
